"""
Cohort domain models.

This module defines canonical data contracts for fleet-level or cohort-based
interpretations generated by the platform.

Used by:
- Cohort GenAI agents
- Executive dashboards
- PDF / email briefings
- Escalation and decision workflows
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------
# Cohort Metrics
# ---------------------------------------------------------------------

class CohortMetric(BaseModel):
    """
    Aggregated metric describing a cohort characteristic.
    """

    name: str = Field(
        ...,
        description="Metric identifier",
        example="elevated_risk_ratio",
    )
    value: float = Field(
        ...,
        description="Computed metric value",
        example=0.18,
    )
    unit: Optional[str] = Field(
        None,
        description="Unit of measure, if applicable",
        example="ratio",
    )
    description: str = Field(
        ...,
        description="Human-readable explanation of the metric",
    )

    class Config:
        frozen = True


# ---------------------------------------------------------------------
# Cohort Anomaly
# ---------------------------------------------------------------------

class CohortAnomaly(BaseModel):
    """
    Detected anomaly or emerging pattern within a cohort.
    """

    title: str = Field(
        ...,
        description="Short anomaly headline",
        example="Spike in fuel system anomalies",
    )
    description: str = Field(
        ...,
        description="Narrative explanation of the anomaly",
    )
    affected_vin_count: int = Field(
        ...,
        ge=1,
        description="Number of VINs affected",
    )
    severity: str = Field(
        ...,
        description="Severity classification",
        example="HIGH",
    )
    related_signals: List[str] = Field(
        default_factory=list,
        description="Relevant signal or HI codes",
    )

    class Config:
        frozen = True


# ---------------------------------------------------------------------
# Cohort Interpretation (Root Model)
# ---------------------------------------------------------------------

class CohortInterpretation(BaseModel):
    """
    Final, auditable cohort-level interpretation output.

    Represents the GenAI-produced understanding of trends, risks,
    and anomalies across a defined vehicle cohort.
    """

    cohort_id: str = Field(
        ...,
        description="Cohort identifier (e.g., fleet, region, model year)",
        example="EU_DIESEL_MY24",
    )

    cohort_description: Optional[str] = Field(
        None,
        description="Optional human-readable cohort description",
    )

    summary: str = Field(
        ...,
        description="High-level natural-language cohort summary",
    )

    metrics: List[CohortMetric] = Field(
        default_factory=list,
        description="Key aggregated cohort metrics",
    )

    anomalies: List[CohortAnomaly] = Field(
        default_factory=list,
        description="Detected anomalies or emerging risk patterns",
    )

    risk_distribution: Optional[Dict[str, int]] = Field(
        None,
        description="Distribution of risk levels across the cohort",
        example={"LOW": 820, "ELEVATED": 140, "HIGH": 32},
    )

    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when interpretation was generated",
    )

    model_version: str = Field(
        ...,
        description="Version of the cohort interpretation logic / prompt set",
        example="v1.0.0",
    )

    class Config:
        frozen = True
        schema_extra = {
            "example": {
                "cohort_id": "EU_DIESEL_MY24",
                "summary": "Overall fleet health remains stable, with localized spikes in fuel system risk.",
                "model_version": "v1.0.0",
            }
        }
