openapi: 3.0.3
info:
  title: GenAI Predictive Interpreter API
  version: "1.1.0"
  description: API for telemetry interpretation, explainability, export, and approval workflows.

servers:
  - url: http://localhost:8000

paths:
  /health:
    get:
      summary: Service health probe
      responses:
        "200":
          description: Healthy response

  /vin/{vin}:
    get:
      summary: Get VIN interpretation
      parameters:
        - in: path
          name: vin
          required: true
          schema:
            type: string
      responses:
        "200":
          description: VIN interpretation payload

  /cohort/{cohort_id}:
    get:
      summary: Get cohort interpretation
      parameters:
        - in: path
          name: cohort_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Cohort interpretation payload

  /action-pack/:
    post:
      summary: Build action pack
      responses:
        "201":
          description: Action pack created

  /chat:
    post:
      summary: Explainability chat response
      responses:
        "200":
          description: Chat reply

  /export/pdf:
    post:
      summary: Export VIN or cohort PDF
      responses:
        "200":
          description: PDF binary
          content:
            application/pdf:
              schema:
                type: string
                format: binary

  /approval:
    post:
      summary: Record approval decision
      responses:
        "200":
          description: Approval record
    get:
      summary: List approval decisions
      responses:
        "200":
          description: Approval record list
