openapi: 3.0.3
info:
  title: GenAI Predictive Interpreter API
  version: "1.1.0"
  description: API for telemetry interpretation, explainability, export, and approval workflows.

servers:
  - url: http://localhost:8000

paths:
  /health:
    get:
      summary: Service health probe
      responses:
        "200":
          description: Healthy response

  /vin/{vin}:
    get:
      summary: Get VIN interpretation
      parameters:
        - in: path
          name: vin
          required: true
          schema:
            type: string
      responses:
        "200":
          description: VIN interpretation payload

  /cohort/{cohort_id}:
    get:
      summary: Get cohort interpretation
      parameters:
        - in: path
          name: cohort_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Cohort interpretation payload

  /cohort/list:
    get:
      summary: List available cohorts
      description: |
        Returns backend-derived cohort registry entries used by dashboard selectors.
        In sample mode, values are read from sample JSON. In databricks mode, values
        are discovered from mart tables.
      responses:
        "200":
          description: Cohort list response
          content:
            application/json:
              schema:
                type: object
                properties:
                  cohorts:
                    type: array
                    items:
                      type: object
                      properties:
                        cohort_id:
                          type: string
                        cohort_description:
                          type: string
                          nullable: true
                      required:
                        - cohort_id
                required:
                  - cohorts

  /action-pack/:
    post:
      summary: Build action pack
      responses:
        "201":
          description: Action pack created

  /chat:
    post:
      summary: Explainability chat response
      description: REST primary transport for bounded explainability chat.
      responses:
        "200":
          description: Chat reply

  /chat/ws:
    get:
      summary: WebSocket chat transport (upgrade endpoint)
      description: |
        Upgrade this endpoint to WebSocket for low-latency fallback.
        Client messages are JSON payloads with message/context/request_id.
      responses:
        "101":
          description: Switching Protocols

  /export/pdf:
    post:
      summary: Export VIN or cohort PDF
      responses:
        "200":
          description: PDF binary
          content:
            application/pdf:
              schema:
                type: string
                format: binary

  /approval:
    post:
      summary: Record approval decision
      responses:
        "200":
          description: Approval record
    get:
      summary: List approval decisions
      responses:
        "200":
          description: Approval record list
